[2025-06-02T17:03:24.460+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_scraper_pipeline.run_scraper manual__2025-06-02T16:36:58.866401+00:00 [queued]>
[2025-06-02T17:03:24.464+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_scraper_pipeline.run_scraper manual__2025-06-02T16:36:58.866401+00:00 [queued]>
[2025-06-02T17:03:24.465+0000] {taskinstance.py:2170} INFO - Starting attempt 7 of 8
[2025-06-02T17:03:24.482+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_scraper> on 2025-06-02 16:36:58.866401+00:00
[2025-06-02T17:03:24.486+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'google_scraper_pipeline', 'run_scraper', 'manual__2025-06-02T16:36:58.866401+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/google_scraper_dag.py', '--cfg-path', '/tmp/tmp89_heftq']
[2025-06-02T17:03:24.488+0000] {standard_task_runner.py:88} INFO - Job 19: Subtask run_scraper
[2025-06-02T17:03:24.485+0000] {standard_task_runner.py:60} INFO - Started process 329 to run task
[2025-06-02T17:03:24.523+0000] {task_command.py:423} INFO - Running <TaskInstance: google_scraper_pipeline.run_scraper manual__2025-06-02T16:36:58.866401+00:00 [running]> on host 4a3ff0e975f7
[2025-06-02T17:03:24.568+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_scraper_pipeline' AIRFLOW_CTX_TASK_ID='run_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-06-02T16:36:58.866401+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-02T16:36:58.866401+00:00'
[2025-06-02T17:03:26.377+0000] {logging_mixin.py:188} INFO - ‚úÖ Depend√™ncias instaladas com sucesso
[2025-06-02T17:03:26.380+0000] {logging_mixin.py:188} INFO - üì¶ A executar comando: python3 /opt/***/dags/google_scraper/scraping/run_scraper_***.py --dias 1
[2025-06-02T17:04:30.087+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-06-02T17:04:30.090+0000] {process_utils.py:131} INFO - Sending 15 to group 329. PIDs of all processes in the group: [357, 329]
[2025-06-02T17:04:30.091+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 329
[2025-06-02T17:04:30.092+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-02T17:04:30.106+0000] {logging_mixin.py:188} INFO - ‚ö†Ô∏è Erro em run_scraper: Task received SIGTERM signal
[2025-06-02T17:04:30.109+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=357, status='terminated', started='17:03:25') (357) terminated with exit code None
[2025-06-02T17:04:30.552+0000] {logging_mixin.py:188} INFO - ‚úÖ Depend√™ncias instaladas com sucesso
[2025-06-02T17:04:30.552+0000] {logging_mixin.py:188} INFO - üì¶ A executar comando: python3 /opt/***/dags/google_scraper/scraping/run_scraper.py --dias 1
[2025-06-02T17:05:30.132+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=329, name='airflow task ru', status='sleeping', started='17:03:23') did not respond to SIGTERM. Trying SIGKILL
[2025-06-02T17:05:30.134+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 329
[2025-06-02T17:05:30.139+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=329, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='17:03:23') (329) terminated with exit code -9
[2025-06-02T17:05:30.140+0000] {standard_task_runner.py:175} ERROR - Job 19 was killed before it finished (likely due to running out of memory)
